## Import Library

In [387]:
import pandas as pd

## Load Dataset

In [388]:
# dataset source: https://www.kaggle.com/datasets/eishatuzzuhra/ai-usage-and-impact-on-students-and-professionals
df = pd.read_csv('../data_analysis/ai_usage_dataset.csv')

df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   User_ID                      300 non-null    str
 1   Age                          277 non-null    str
 2   Gender                       290 non-null    str
 3   Country                      290 non-null    str
 4   User_Type                    300 non-null    str
 5   Education_Level              287 non-null    str
 6   Profession                   285 non-null    str
 7   Monthly_Income               290 non-null    str
 8   AI_Tool                      289 non-null    str
 9   AI_Purpose                   287 non-null    str
 10  AI_Usage_Hours_Per_Day       293 non-null    str
 11  Tasks_Performed              282 non-null    str
 12  Monthly_AI_Cost              288 non-null    str
 13  Productivity_Score           284 non-null    float64
 14  Accuracy_Rating              285 non-null    float64
 15  Satisfaction_Score           293 non-null    float64
 16  Time_Saved_Hours_Per_Week    290 non-null    str
 17  Work_or_Study_Hours_Per_Day  291 non-null    str
 18  Would_Recommend              295 non-null    str
dtypes: float64(3), str(16)
memory usage: 44.7 KB

       Productivity_Score  Accuracy_Rating  Satisfaction_Score
count          284.000000       285.000000          293.000000
mean             5.230282         3.428070            6.146758
std              1.817193         0.855338            1.517805
min              1.600000         2.000000            3.000000
25%              3.900000         3.000000            5.000000
50%              5.000000         4.000000            6.000000
75%              6.500000         4.000000            7.000000
max             10.000000         5.000000           10.000000

## Overview Dataset

In [389]:
df.head(10)

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
0,U0269,30,Male,United Kingdom,Professional,Master's,Business Analyst,5421,ChatGPT,Office Work,2 hrs,Data analysis using AI-powered analytics tools...,NaN,5.3,4.0,7.0,3.9,7.3,Yes
1,U0217,30,Male,United States,Professional,Bachelor's,Customer Support Specialist,8903,ChatGPT,Customer Support,5.7,Resolving customer inquiries using AI chatbot ...,0,9.9,3.0,9.0,11.4,8.4 hrs,Yes
2,U0152,17,Male,Canada,Student,NaN,Computer Science Student,402,Chat GPT,Coding,1 hrs,NaN,20,3.2,2.0,4.0,5.2,6.7,No
3,U0264,35,FEMALE,Brazil,Professional,Bachelor's,Desenvolvedora de Software / Software Developer,1367,Meta AI,Coding,1.7,"Usar GitHub Copilot para autocompletar código,...",20,5.6,4.0,5.0,6.4,9.6,Maybe
4,U0263,19,Female,Canada,Student,Undergraduate,Biology Student,438,Perplexity AI,NaN,4.1,Using AI to generate study summaries for exam ...,0,4.7,4.0,7.0,9.2,6.2,Yes
5,U0225,19,NaN,United States,Student,Undergraduate,Business Analytics Student,774,Meta AI,Data Analysis,1.5,"Statistical analysis on datasets, data visuali...",0,5.0,3.0,6.0,2.9,7.4,No
6,U0246,32,Male,france,Professional,Bachelor's,Développeur Full Stack,4466,ChatGPT,Coding,1.2,"Automated code review with AI-powered linters,...",20,3.0,2.0,5.0,6.6,6.4,Yes
7,U0177,32,Male,Philippines,Professional,High School,Social Media Content Creator,486,ChatGPT,Content Creation,2,Creating Instagram/TikTok captions with AI wri...,0,6.5,2.0,5.0,3.2 hrs,6.4,Yes
8,U0207,16,Male,Philippines,Student,Undergraduate,Digital Media Production Student,132,Claude,Content Creation,1.6 hrs,"Creating YouTube video scripts, Designing soci...",30,4.7,4.0,6.0,3.8,3.8,Yes
9,U0167,40,male,india,Professional,High School,NaN,1595,ChatGPT,Writing,1.7,"Email copywriting, Social media post creation,...",10,NaN,2.0,5.0,7.5,9.4,Maybe

In [390]:
df.tail(10)

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
290,U0287,22,Other,India,Student,undergrad,Mechanical Engineering Student,0,Meta AI,Studying,2.4,Generating solved examples for thermodynamics ...,20,3.4,4.0,6.0,4.8,6.2,No
291,U0147,39,Male,brazil,Professional,Diploma,Analista de Dados,894,ChatGPT,Data Analysis,2.8,NaN,20,7.9,4.0,9.0,3.9,9.2,Yes
292,U0134,27,Other,Canada,Student,Undergraduate,Digital Media Production Student,675,Claude,Content Creation,1.2,"Generating video scripts and storyboards, Crea...",20,4.1,3.0,6.0,1.1,7.6,Yes
293,U0158,31,Male,Australia,Student,Undergraduate,NaN,204,Meta AI,Writing,0.6 hrs,"Essay drafting and structuring, grammar and cl...",0,3.3,2.0,4.0,3.6,5.6,No
294,U0174,32,Male,Canada,Student,High School,Computer Science Student,0,claude,Coding,3.9,"Debugging code errors, generating code snippet...",0,5.7,3.0,6.0,7.3,4.8,Maybe
295,U0066,NaN,Female,United States,Professional,Bachelor's,NaN,8255,Microsoft Copilot,NaN,1.8,"Code debugging with AI pair programming tools,...",0,1.8,3.0,4.0,NaN,12.2,No
296,U0094,43,Male,Nigeria,Professional,Diploma,Multimedia Content Producer,NaN,ChatGPT,Content Creation,1.2,Writing blog articles with AI writing assistan...,0,4.7,3.0,NaN,1,10.9,No
297,U0136,48,Male,Brazil,Professional,Diploma,Desenvolvedor de Sistemas (Systems Developer),544,Google Gemini,Coding,5.5,"Code debugging and optimization with AI tools,...",0,7.8,4.0,7.0,11.5,8.4,Yes
298,U0002,31,Female,Pakistan,Professional,Diploma,Junior Software Developer,448,ChatGPT,Coding,0.7 hrs,"Automated code generation using AI assistants,...",0,4.3,3.0,4.0,1.7,9.5,No
299,U0130,36 yrs,Male,United States,Professional,Diploma,Software Developer,6766,Chat GPT,Coding,2.8,"Debugging code with AI-assisted analysis, gene...",0,5.4,4.0,7.0,6.2,8.2,Yes

## Check Duplicate Data

In [391]:
df.duplicated().sum()

np.int64(12)

### Delete Duplicate Data

In [392]:
df = df.drop_duplicates()

df.info()
df.describe()

<class 'pandas.DataFrame'>
Index: 288 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   User_ID                      288 non-null    str
 1   Age                          265 non-null    str
 2   Gender                       278 non-null    str
 3   Country                      278 non-null    str
 4   User_Type                    288 non-null    str
 5   Education_Level              276 non-null    str
 6   Profession                   274 non-null    str
 7   Monthly_Income               278 non-null    str
 8   AI_Tool                      278 non-null    str
 9   AI_Purpose                   275 non-null    str
 10  AI_Usage_Hours_Per_Day       281 non-null    str
 11  Tasks_Performed              271 non-null    str
 12  Monthly_AI_Cost              276 non-null    str
 13  Productivity_Score           274 non-null    float64
 14  Accuracy_Rating              274 non-null    float64
 15  Satisfaction_Score           281 non-null    float64
 16  Time_Saved_Hours_Per_Week    278 non-null    str
 17  Work_or_Study_Hours_Per_Day  279 non-null    str
 18  Would_Recommend              283 non-null    str
dtypes: float64(3), str(16)
memory usage: 45.0 KB

       Productivity_Score  Accuracy_Rating  Satisfaction_Score
count          274.000000       274.000000          281.000000
mean             5.235036         3.416058            6.131673
std              1.821789         0.857138            1.526116
min              1.600000         2.000000            3.000000
25%              3.900000         3.000000            5.000000
50%              5.000000         3.500000            6.000000
75%              6.500000         4.000000            7.000000
max             10.000000         5.000000           10.000000

## Check Missing Value

In [393]:
df.isnull().sum()

User_ID                         0
Age                            23
Gender                         10
Country                        10
User_Type                       0
Education_Level                12
Profession                     14
Monthly_Income                 10
AI_Tool                        10
AI_Purpose                     13
AI_Usage_Hours_Per_Day          7
Tasks_Performed                17
Monthly_AI_Cost                12
Productivity_Score             14
Accuracy_Rating                14
Satisfaction_Score              7
Time_Saved_Hours_Per_Week      10
Work_or_Study_Hours_Per_Day     9
Would_Recommend                 5
dtype: int64

### Check Age Column

In [394]:
# Check data where 'Age' is null/NaN
df[df['Age'].isnull()]

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
29,U0132,NaN,Male,Australia,Student,NaN,Business Administration Student,0,ChatGPT,Research,5.4,"Literature review and source compilation, Data...",0,7.2,4.0,8.0,10.7,4.8,No
49,U0060,NaN,Female,Philippines,Student,Bachelor's,NaN,190,ChatGPT,Research,7.7,"Literature review and paper summarization, Dat...",NaN,8.4,5.0,10.0,13.6,6.8,Yes
52,U0028,NaN,Other,Pakistan,Student,Undergraduate,English Literature Student,100,ChatGPT,Writing,1.2,"Essay drafting and outline generation, academi...",50,5.8,4.0,7.0,NaN,5.7,Yes
74,U0234,NaN,Female,Nigeria,Student,Bachelor's,English Literature Student,NaN,ChatGPT,Writing,2.1,"Essay composition and structure planning, gram...",0,4.7,5.0,8.0,NaN,5.9,Yes
78,U0192,NaN,Male,Kenya,Professional,High School,Administrative Assistant,557,ChatGPT,Office Work,9.9 hrs,NaN,0,8.8,5.0,9.0,16.2,8.5,Yes
95,U0032,NaN,Male,Germany,Student,High School,German Literature Student,366,ChatGPT,Writing,0.6,"Essay structure planning, grammar and spelling...",$25,4.1,NaN,6.0,3,7.6,Yes
96,U0073,NaN,Male,Canada,Student,Undergraduate,Environmental Science Student,397,Google Gemini,Research,5.4,"Literature review and paper summarization, Dat...",0,9.3,3.0,8.0,13.1,6.5,Yes
123,U0154,NaN,MALE,Pakistan,Student,Bachelor's,Software Engineering Student,83,Claude,Studying,2.3,NaN,20,6.1,3.0,5.0,2.3,6.4,Maybe
151,U0253,NaN,Female,Canada,Professional,Bachelor's,Customer Support Specialist,6705,DeepSeek,Customer Support,9.7,Responding to customer inquiries using AI-powe...,20,7.7,5.0,9.0,NaN,11.6,Yes
166,U0166,NaN,Female,Australia,Student,Undergraduate,Biomedical Science Student,133,ChatGPT,Studying,1.2,Using AI to generate study summaries of comple...,0,2.6,4.0,7.0,5.3,7.1,Yes
194,U0122,NaN,Female,Canada,Student,Undergraduate,Psychology Student,624,Google Gemini,Research,0.9 hrs,"Literature review summarization, research pape...",0,4.4,3.0,5.0,0.1,7.4 hrs,Yes
207,U0048,NaN,Female,United States,Professional,Bachelor's,NaN,NaN,NaN,Writing,3.1,Draft blog posts and marketing copy with AI wr...,30,5.6,3.0,7.0,5.2,8.4,Yes
213,U0018,NaN,Male,United States,Professional,Master's,Content Strategist,10311,Google Gemini,Writing,2.1,"Using AI for blog drafting, editing article co...",20,4.2,3.0,5.0,5.4,10.5,Maybe
218,U0038,NaN,male,Nigeria,Student,Undergraduate,English Literature Student,98,Claude,Writing,1.7,"Essay writing and structure planning, Grammar ...",20,3.5,3.0,6.0,2.9,7.7,Yes
220,U0185,NaN,Male,Brazil,Student,Bachelor's,Digital Media Production Student,243,Claude,Content Creation,2.8,"Video editing and effects using AI tools, AI-a...",100,5.4,3.0,6.0,6.8,8.5,Yes
222,U0247,NaN,Female,australia,Professional,Master's,Data Analyst / Business Intelligence Specialist,"$3,462",Google Gemini,Data Analysis,4.5,Cleaning and preprocessing datasets using Pyth...,0,5.6,4.0,5.0,5.5,6.7,Maybe
232,U0155,NaN,Male,United Kingdom,Professional,Diploma,Content Writer,2303,Perplexity AI,Writing,4.4,Drafting blog articles and web copy with AI as...,20,5.8,5.0,9.0,11.3,7.8,Yes
233,U0013,NaN,Male,Canada,Professional,HS,Junior Web Developer,3779,ChatGPT,Coding,5.7,Writing JavaScript code with AI code completio...,0,6.7,2.0,5.0,13,6.6,Maybe
236,U0275,NaN,Male,India,Student,High School,Statistics Student,$0,Google Gemini,Data Analysis,2,"Analyzing survey datasets using Python, Creati...",0,3.6,5.0,5.0,3.6,4.4,Maybe
239,U0065,NaN,male,United Kingdom,Student,Bachelor's,Mechanical Engineering Student,334,ChatGPT,Studying,4.1,"Explaining complex physics concepts, solving d...",20,5.2,3.0,7.0,8.4,5.9,Yes
263,U0040,NaN,Male,United Kingdom,Professional,Bachelor's,NaN,4102,Google Gemini,Content Creation,2.5,Writing blog posts and articles using AI writi...,10,6.1,5.0,7.0,5.6,7.5,Yes
264,U0183,NaN,Other,United States,Student,Bachelor's,English Literature Student,390,DeepSeek,Writing,7.9,"Essay outlining and structure planning, gramma...",0,8.9,4.0,9.0,14.2 hrs,6,Yes
295,U0066,NaN,Female,United States,Professional,Bachelor's,NaN,8255,Microsoft Copilot,NaN,1.8,"Code debugging with AI pair programming tools,...",0,1.8,3.0,4.0,NaN,12.2,No

In [395]:
# Check value in 'Age'
df['Age'].value_counts()

Age
23        26
22        23
20        14
32        12
17        11
31        11
21        10
24        10
18         8
27         8
30         7
35         7
29         7
39         7
19         6
16         6
28         6
26         6
25         6
41         6
36         5
63         5
40         4
44         4
34         4
49         4
48         4
43         3
33         3
61         2
23 yrs     2
37         2
97         2
54         2
47         2
28 yrs     2
55         2
38         2
16 yrs     1
45         1
21 yrs     1
47 yrs     1
46         1
25 yrs     1
30 yrs     1
56         1
58         1
39 yrs     1
17 yrs     1
53         1
64         1
36 yrs     1
Name: count, dtype: int64

In [396]:
# Clean ' yrs' and convert to float temporary
df['Age'] = df['Age'].str.extract(r'(\d+)').astype(float)

df['Age'].value_counts()

Age
23.0    28
22.0    23
20.0    14
17.0    12
32.0    12
21.0    11
31.0    11
24.0    10
30.0     8
28.0     8
18.0     8
39.0     8
27.0     8
35.0     7
16.0     7
29.0     7
25.0     7
19.0     6
36.0     6
26.0     6
41.0     6
63.0     5
40.0     4
44.0     4
34.0     4
49.0     4
48.0     4
43.0     3
33.0     3
47.0     3
61.0     2
37.0     2
97.0     2
54.0     2
55.0     2
38.0     2
45.0     1
46.0     1
56.0     1
58.0     1
53.0     1
64.0     1
Name: count, dtype: int64

In [397]:
# mean, median, modus in 'Age'
print(df['Age'].mean())
print(df['Age'].median())
print(df['Age'].mode()[0])

30.12452830188679
27.0
23.0

In [398]:
# Fill the NaN 'Age' with median value of 'Age'
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Age'] = df['Age'].astype(int)

df['Age'].isnull().sum()

np.int64(0)

In [399]:
df['Age'].value_counts()

Age
27    31
23    28
22    23
20    14
17    12
32    12
21    11
31    11
24    10
30     8
28     8
18     8
39     8
35     7
16     7
29     7
25     7
19     6
36     6
26     6
41     6
63     5
40     4
44     4
34     4
49     4
48     4
43     3
33     3
47     3
61     2
37     2
97     2
54     2
55     2
38     2
45     1
46     1
56     1
58     1
53     1
64     1
Name: count, dtype: int64

In [400]:
df.info()

<class 'pandas.DataFrame'>
Index: 288 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   User_ID                      288 non-null    str
 1   Age                          288 non-null    int64
 2   Gender                       278 non-null    str
 3   Country                      278 non-null    str
 4   User_Type                    288 non-null    str
 5   Education_Level              276 non-null    str
 6   Profession                   274 non-null    str
 7   Monthly_Income               278 non-null    str
 8   AI_Tool                      278 non-null    str
 9   AI_Purpose                   275 non-null    str
 10  AI_Usage_Hours_Per_Day       281 non-null    str
 11  Tasks_Performed              271 non-null    str
 12  Monthly_AI_Cost              276 non-null    str
 13  Productivity_Score           274 non-null    float64
 14  Accuracy_Rating              274 non-null    float64
 15  Satisfaction_Score           281 non-null    float64
 16  Time_Saved_Hours_Per_Week    278 non-null    str
 17  Work_or_Study_Hours_Per_Day  279 non-null    str
 18  Would_Recommend              283 non-null    str
dtypes: float64(3), int64(1), str(15)
memory usage: 45.0 KB

## Cleaning Bagian 1

### Check Gender Column

In [401]:
df[df['Gender'].isnull()]

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
5,U0225,19,NaN,United States,Student,Undergraduate,Business Analytics Student,774,Meta AI,Data Analysis,1.5,"Statistical analysis on datasets, data visuali...",0,5.0,3.0,6.0,2.9,7.4,No
23,U0141,29,NaN,United Kingdom,Student,High School,Computer Science Student,0,Grammarly,Coding,2.6,"Debugging Python code with AI assistants, gene...",10,3.7,4.0,7.0,4.8,6.2,Yes
38,U0071,30,NaN,India,Professional,Master's,Data Analytics Manager,1699,Perplexity AI,Data Analysis,5.5,Building predictive models with Python and sci...,10,NaN,4.0,8.0,6.5,7.5,Yes
43,U0070,17,NaN,Brazil,Student,Undergraduate,NaN,234,ChatGPT,Studying,5.1,"Using AI to solve physics problems, generating...",0,8.3,5.0,9.0,11.4,7.2,Yes
53,U0125,26,NaN,Nigeria,Student,High School,Computer Science Student,0,ChatGPT,Coding,0.6,"Debugging Python code with AI code analysis, W...",0,3.2,2.0,5.0,2.2 hrs,8.8,Yes
70,U0131,35,NaN,United States,Professional,Diploma,Administrative Assistant,5966,ChatGPT,Office Work,4.9,Data entry and document formatting with AI too...,20,5.7,3.0,5.0,11.5,9.3,Yes
99,U0221,31,NaN,Brazil,Student,High School,Software Development Student,191,Claude,Coding,1.9,"Debugging Python code with AI assistance, gene...",0,4.8,4.0,7.0,4.8,5.1,Yes
117,U0143,20,NaN,Pakistan,Student,Undergraduate,Digital Marketing Student,0,Claude,Content Creation,3.4,"AI-assisted blog writing and SEO optimization,...",10,6.5,3.0,6.0,7.2,4.6,Yes
127,U0076,17,NaN,Philippines,Student,Master's,Creative Writing Student,130,Claude,NaN,2.4,"Essay structuring and outlining, narrative dev...",20,4.8,4.0,8.0,4.7,3.2,Yes
131,U0017,30,NaN,Pakistan,Student,NaN,Software Engineering Student,67,ChatGPT,Coding,1.4,"Debugging code with AI assistance, generating ...",20,2.9,3.0,3.0,0.8,5.6,No

In [402]:
df['Gender'].isnull().sum()

np.int64(10)

In [403]:
df['Gender'].value_counts()

Gender
Male          116
Female         99
male           12
Other          12
M              11
F              10
MALE            6
FEMALE          5
other           3
female          3
Non-binary      1
Name: count, dtype: int64

In [404]:
# Gender is only two (male or female).
# But sometimes, there is a option to not display a gender. So, in addition to male and female, i will replace with 'Not Display'. (I don't support LGBTQ)
df['Gender'] = df['Gender'].replace({
   'male' : 'Male', 'M': 'Male', 'MALE': 'Male',
   'F': 'Female', 'FEMALE': 'Female', 'female': 'Female',
   'Other': 'Not Display', 'other': 'Not Display', 'Non-binary': 'Not Display'
})

df['Gender'] = df['Gender'].fillna('Not Display')

df['Gender'].value_counts()

Gender
Male           145
Female         117
Not Display     26
Name: count, dtype: int64

### Check Country Column

In [405]:
df[df['Country'].isnull()]

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
36,U0258,16,Female,NaN,Student,Undergraduate,NaN,63,Perplexity AI,Research,1.9,"Literature review and paper summarization, Dat...",0,3.5,3.0,5.0,3,5.4,Maybe
66,U0137,23,Not Display,NaN,Student,Master's,Software Engineering Student,0,Microsoft Copilot,Coding,1,"Code debugging and optimization, API developme...",20,3.3,3.0,5.0,2.6,6.2,Yes
128,U0011,23,Female,NaN,Professional,Bachelor's,Customer Support Specialist,5268,Perplexity AI,Customer Support,1.2,"AI chatbot response review and optimization, a...",0,2.4,4.0,NaN,0.4,8.8,No
155,U0023,21,Male,NaN,Student,High School,English Literature Student,59,ChatGPT,Writing,3,"Essay structuring and outlining, grammar check...",25,4.5,4.0,7.0,4.9,8.4,Yes
173,U0213,22,Female,NaN,Student,Bachelor's,German Literature and Comparative Studies Student,0,ChatGPT,Writing,2.5,"Essay drafting and structuring, Literature ana...",10,5.2,2.0,5.0,4.4,7.8,No
176,U0087,17,Male,NaN,Student,undergrad,Digital Media & Film Production Student,387,Microsoft Copilot,Content Creation,1.5,"Video editing with AI-assisted color grading, ...",10,6.2,3.0,6.0,7.5,NaN,No
177,U0175,25,Male,NaN,Professional,PhD,AI Content Strategist,1632,ChatGPT,Content Creation,4.4,Generating blog articles and marketing copy wi...,$0,7.8,4.0,9.0,7.1,5.8,Yes
193,U0025,17,Not Display,NaN,Student,Undergraduate,Environmental Science Student,NaN,ChatGPT,Research,6.1,"Literature review and source analysis, Data in...",30,7.0,4.0,8.0,8.9,7.8,Yes
212,U0266,28,Not Display,NaN,Professional,PhD,Research Scientist / Data Analyst,1208,Perplexity AI,Office Work,1,"Automated report generation using AI, Data ana...",20,2.6,4.0,4.0,NaN,8.3,No
240,U0080,22,Male,NaN,Student,High School,Computer Science Student,158,ChatGPT,Coding,1.6,"Debugging code with AI assistance, Learning Py...",10,3.1,4.0,6.0,5.9,8.4,Yes

In [406]:
df['Country'].isnull().sum()

np.int64(10)

In [407]:
df['Country'].value_counts()

Country
India                       40
United States               33
Canada                      29
Pakistan                    28
United Kingdom              25
Philippines                 23
Brazil                      22
Australia                   19
Nigeria                     17
Germany                     13
France                       9
Kenya                        6
brazil                       4
india                        3
canada                       2
france                       1
U.K.                         1
United States of America     1
philippines                  1
australia                    1
Name: count, dtype: int64

In [408]:
# I will fill the NaN value in column 'Country' with 'Not Display', make it consist with other column like 'Gender'.
# And replace the lowercase with capital in the first alphabet

df['Country'] = df['Country'].fillna('Not Display')
df['Country'] = df['Country'].replace({
   'brazil': 'Brazil', 'india': 'India', 'canada': 'Canada',
   'france': 'France', 'U.K.': 'United Kingdom',
   'United States of America': 'United States',
   'philippines': 'Philippines', 'australia': 'Australia'
})

df['Country'].value_counts()

Country
India             43
United States     34
Canada            31
Pakistan          28
United Kingdom    26
Brazil            26
Philippines       24
Australia         20
Nigeria           17
Germany           13
France            10
Not Display       10
Kenya              6
Name: count, dtype: int64

In [409]:
df['Country'].isnull().sum()

np.int64(0)

### Check User_Type Column

In [410]:
df['User_Type'].isnull().sum()

np.int64(0)

In [411]:
df['User_Type'].value_counts()

User_Type
Student         151
Professional    137
Name: count, dtype: int64

### Check Education_Level Column

In [412]:
df['Education_Level'].isnull().sum()

np.int64(12)

In [413]:
df[df['Education_Level'].isnull()]

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
2,U0152,17,Male,Canada,Student,NaN,Computer Science Student,402,Chat GPT,Coding,1 hrs,NaN,20,3.2,2.0,4.0,5.2,6.7,No
24,U0205,24,Male,United Kingdom,Student,NaN,Mechanical Engineering Student,444,Google Gemini,Studying,1.2,"Analyzing complex physics problems, generating...",0,3.8,3.0,5.0,3,7.2,No
29,U0132,27,Male,Australia,Student,NaN,Business Administration Student,0,ChatGPT,Research,5.4,"Literature review and source compilation, Data...",0,7.2,4.0,8.0,10.7,4.8,No
94,U0049,25,Female,United Kingdom,Professional,NaN,Junior Software Developer,2945,Perplexity AI,Coding,NaN,Writing Python scripts with AI code completion...,20,9.4,3.0,8.0,15.1,11.3,Yes
131,U0017,30,Not Display,Pakistan,Student,NaN,Software Engineering Student,67,ChatGPT,Coding,1.4,"Debugging code with AI assistance, generating ...",20,2.9,3.0,3.0,0.8,5.6,No
132,U0100,20,Not Display,United States,Student,NaN,Data Science Student,698,Google Gemini,Research,1.2,"Literature review automation, research paper s...",0,3.7,3.0,4.0,1.7,4.7,No
159,U0104,26,Male,Pakistan,Student,NaN,Mechanical Engineering Student,54,ChatGPT,Research,2.7,"Literature review automation, research paper s...",20,NaN,3.0,5.0,5 hrs,6.9,Maybe
169,U0129,24,Female,Pakistan,Student,NaN,English Literature Student,95,Microsoft Copilot,Writing,3.7,"Essay structuring and brainstorming, Grammar a...",0,7.7,4.0,7.0,9.9,9,Maybe
182,U0169,39,Female,Philippines,Professional,NaN,Digital Content Creator / Social Media Manager,1192,ChatGPT,Content Creation,1.4,NaN,30,3.5,4.0,6.0,3.8,6.7,Yes
188,U0072,23,Female,India,Student,NaN,Computer Science Student,50,Grammarly,Coding,9.8,"Debugging code with AI assistance, generating ...",$0,9.1,4.0,9.0,15.8,5.2,Yes
242,U0015,18,Male,Canada,Student,NaN,Business Administration Student,56,Google Gemini,Studying,1.7,Using AI chatbots to explain complex business ...,30,4.9,3.0,5.0,1.9,4.3,Yes
281,U0276,20,Female,Philippines,Student,NaN,English Literature Student,93,ChatGPT,Writing,2.3,"Essay drafting and structure planning, grammar...",10,4.2,3.0,4.0,3.4,6.1,No

In [414]:
df['Education_Level'].value_counts()

Education_Level
Bachelor's           69
Undergraduate        60
Master's             48
High School          44
Diploma              25
PhD                  14
undergrad             3
BA/BSc                2
Ph.D.                 2
Masters               2
Bachelors             2
high school           1
MA/MSc                1
master's degree       1
bachelor's degree     1
HS                    1
Name: count, dtype: int64

In [415]:
df['Education_Level'] = df['Education_Level'].fillna('Not Display')
df['Education_Level'] = df['Education_Level'].replace({
   'undergrad': 'Undergraduate', 'BA/BSc': "Bachelor's", 'Ph.D.': 'PhD',
   'Masters': "Master's", 'Bachelors': "Bachelor's", 'high school': 'High School',
   'MA/MSc': "Master's", "master's degree" : "Master's", "bachelor's degree" : "Bachelor's",
   'HS': 'High School'
})

df['Education_Level'].value_counts()

Education_Level
Bachelor's       74
Undergraduate    63
Master's         52
High School      46
Diploma          25
PhD              16
Not Display      12
Name: count, dtype: int64

In [416]:
df['Education_Level'].isnull().sum()

np.int64(0)

### Check Profession Column

In [417]:
df['Profession'].isnull().sum()

np.int64(14)

In [418]:
df[df['Profession'].isnull()]

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
9,U0167,40,Male,India,Professional,High School,NaN,1595,ChatGPT,Writing,1.7,"Email copywriting, Social media post creation,...",10,NaN,2.0,5.0,7.5,9.4,Maybe
15,U0138,16,Female,Canada,Student,Master's,NaN,324,Microsoft Copilot,Coding,7.1,NaN,20,NaN,2.0,5.0,11.6,3,No
36,U0258,16,Female,Not Display,Student,Undergraduate,NaN,63,Perplexity AI,Research,1.9,"Literature review and paper summarization, Dat...",0,3.5,3.0,5.0,3,5.4,Maybe
43,U0070,17,Not Display,Brazil,Student,Undergraduate,NaN,234,ChatGPT,Studying,5.1,"Using AI to solve physics problems, generating...",0,8.3,5.0,9.0,11.4,7.2,Yes
49,U0060,27,Female,Philippines,Student,Bachelor's,NaN,190,ChatGPT,Research,7.7,"Literature review and paper summarization, Dat...",NaN,8.4,5.0,10.0,13.6,6.8,Yes
115,U0037,63,Male,Brazil,Professional,Diploma,NaN,418,ChatGPT,Writing,1.6,"Drafting advertising copy with AI assistance, ...",NaN,4.9,4.0,5.0,4.9,8.5,No
189,U0245,63,Female,India,Professional,High School,NaN,1320,Claude,Office Work,1.7,"Email management and scheduling, document prep...",NaN,5.2,3.0,6.0,3.5 hrs,9.4,Yes
195,U0031,20,Male,Canada,Student,Undergraduate,NaN,415,Microsoft Copilot,Research,3,"Literature review and paper summarization, Lab...",0,4.4,3.0,5.0,3.1,5.5,Yes
207,U0048,27,Female,United States,Professional,Bachelor's,NaN,NaN,NaN,Writing,3.1,Draft blog posts and marketing copy with AI wr...,30,5.6,3.0,7.0,5.2,8.4,Yes
245,U0103,41,Male,India,Professional,Diploma,NaN,627,Grammarly,Customer Support,0.7,"Handling customer inquiries via AI chatbots, r...",0,2.3,4.0,5.0,3,6.9,Yes
263,U0040,27,Male,United Kingdom,Professional,Bachelor's,NaN,4102,Google Gemini,Content Creation,2.5,Writing blog posts and articles using AI writi...,10,6.1,5.0,7.0,5.6,7.5,Yes
279,U0267,16,Female,United States,Student,PhD,NaN,707,ChatGPT,Data Analysis,1.1,"Statistical modeling of biological datasets, m...",0,5.1,3.0,7.0,5.1,4.9,Yes
293,U0158,31,Male,Australia,Student,Undergraduate,NaN,204,Meta AI,Writing,0.6 hrs,"Essay drafting and structuring, grammar and cl...",0,3.3,2.0,4.0,3.6,5.6,No
295,U0066,27,Female,United States,Professional,Bachelor's,NaN,8255,Microsoft Copilot,NaN,1.8,"Code debugging with AI pair programming tools,...",0,1.8,3.0,4.0,NaN,12.2,No

In [419]:
df['Profession'].value_counts()

Profession
English Literature Student                          24
Computer Science Student                            18
Biology Student                                     11
Mechanical Engineering Student                      10
Data Science Student                                10
                                                    ..
Research Scientist                                   1
Academic Research Professor and Technical Writer     1
Analista de Dados                                    1
Multimedia Content Producer                          1
Desenvolvedor de Sistemas (Systems Developer)        1
Name: count, Length: 126, dtype: int64

In [420]:
df['Profession'] = df['Profession'].fillna(df['Profession'].mode()[0])

df['Profession'].isnull().sum()

np.int64(0)

In [421]:
df['Profession'].value_counts().head()

Profession
English Literature Student        38
Computer Science Student          18
Biology Student                   11
Mechanical Engineering Student    10
Data Science Student              10
Name: count, dtype: int64

## Cleaning Bagian 2

In [422]:
df.isnull().sum()

User_ID                         0
Age                             0
Gender                          0
Country                         0
User_Type                       0
Education_Level                 0
Profession                      0
Monthly_Income                 10
AI_Tool                        10
AI_Purpose                     13
AI_Usage_Hours_Per_Day          7
Tasks_Performed                17
Monthly_AI_Cost                12
Productivity_Score             14
Accuracy_Rating                14
Satisfaction_Score              7
Time_Saved_Hours_Per_Week      10
Work_or_Study_Hours_Per_Day     9
Would_Recommend                 5
dtype: int64

### Checking Monthly_Income

In [423]:
df['Monthly_Income'].tail(60)

234      672
236      $0
237      135
239      334
240      158
241        0
242       56
243      118
244       80
245      627
246      863
247        0
248      167
249       73
250      NaN
252     1114
253    $528
254      524
255        0
256      915
257      483
258     3795
259     5976
260     3513
261      110
262     2690
263     4102
264      390
265      312
266      595
269      983
270        0
272       76
273     1991
274        0
275        0
276      435
277      678
278     4006
279      707
280      523
281       93
282     5785
283     3114
284     4186
285        0
286      243
287      540
288      152
289     1148
290        0
291      894
292      675
293      204
294        0
295     8255
296      NaN
297      544
298      448
299     6766
Name: Monthly_Income, dtype: str

In [424]:
# Extranct digits, change data type to float, fill missing value with median, and change data type to integer
df['Monthly_Income'] = df['Monthly_Income'].str.extract(r'(\d+)').astype(float)
df['Monthly_Income'] = df['Monthly_Income'].fillna(df['Monthly_Income'].median())
df['Monthly_Income'] = df['Monthly_Income'].astype(int)

In [425]:
df['Monthly_Income'].isnull().sum()

np.int64(0)

### Check AI_Tool

In [426]:
df['AI_Tool'].isnull().sum()

np.int64(10)

In [427]:
df['AI_Tool'].value_counts()

AI_Tool
ChatGPT              110
Google Gemini         37
Microsoft Copilot     30
Claude                29
Perplexity AI         23
Grammarly             14
Meta AI               10
DeepSeek               9
chatgpt                4
Chat GPT               3
Chatgpt                2
Copilot                2
claude                 2
Gemini                 1
gemini                 1
copilot                1
Name: count, dtype: int64

In [428]:
df['AI_Tool'] = df['AI_Tool'].replace({
   'chatgpt': 'ChatGPT', 'Chat GPT': 'ChatGPT', 'Chatgpt': 'ChatGPT',
   'Copilot' : 'Microsoft Copilot', 'claude' : 'Claude', 'Gemini' : 'Google Gemini',
   'gemini' : 'Google Gemini', 'copilot': 'Microsoft Copilot'
})

df['AI_Tool'] = df['AI_Tool'].fillna(df['AI_Tool'].mode()[0])

df['AI_Tool'].isnull().sum()

np.int64(0)

In [429]:
df['AI_Tool'].value_counts()

AI_Tool
ChatGPT              129
Google Gemini         39
Microsoft Copilot     33
Claude                31
Perplexity AI         23
Grammarly             14
Meta AI               10
DeepSeek               9
Name: count, dtype: int64

### Check AI_Purpose

In [430]:
df['AI_Purpose'].isnull().sum()

np.int64(13)

In [431]:
df['AI_Purpose'].value_counts()

AI_Purpose
Coding              65
Writing             49
Studying            39
Research            38
Content Creation    28
Data Analysis       25
Customer Support    20
Office Work         11
Name: count, dtype: int64

In [432]:
df['AI_Purpose'] = df['AI_Purpose'].fillna(df['AI_Purpose'].mode()[0])

print(df['AI_Purpose'].isnull().sum())
df['AI_Purpose'].value_counts()

0

AI_Purpose
Coding              78
Writing             49
Studying            39
Research            38
Content Creation    28
Data Analysis       25
Customer Support    20
Office Work         11
Name: count, dtype: int64

### Check AI_Usage_Hours_Per_Da

In [433]:
df['AI_Usage_Hours_Per_Day'].isnull().sum()

np.int64(7)

In [434]:
df['AI_Usage_Hours_Per_Day'].value_counts()

AI_Usage_Hours_Per_Day
1.5        13
1.6        11
1.9        11
1.7        10
1.2        10
           ..
8.1         1
3.9 hrs     1
4.9 hrs     1
8.6         1
7.9         1
Name: count, Length: 89, dtype: int64

In [ ]:
df['AI_Usage_Hours_Per_Day'] = df['AI_Usage_Hours_Per_Day'].astype(str)
df['AI_Usage_Hours_Per_Day'] = df['AI_Usage_Hours_Per_Day'].fillna(df['AI_Usage_Hours_Per_Day'].mode()[0])
# df['AI_Usage_Hours_Per_Day'] = df['AI_Usage_Hours_Per_Day'].extract(r'(\d+)').astype(float)

print(df['AI_Usage_Hours_Per_Day'].isnull().sum())
df['AI_Usage_Hours_Per_Day'].value_counts()

0

AI_Usage_Hours_Per_Day
1.5        20
1.6        11
1.9        11
1.7        10
1.2        10
           ..
8.1         1
3.9 hrs     1
4.9 hrs     1
8.6         1
7.9         1
Name: count, Length: 89, dtype: int64